name: M4
markdown: kramdown
highlighter: rouge
allurl: albi3ro.github.io/M4
baseurl: /M4
permalink: /:title:output_ext
gems:
  - jekyll-feed

title: Metals, Magnets, and Miscellaneous Materials
email: chrissie.c.l@gmail.com
description: Blog Introduction to Computational Condensed Matter Physics

twitter_username: PyrochloreLee
github_username: albi3ro
